#!/usr/bin/env Rscript

source_file <- "notebooks/support/probability-distributions/support.Rmd"
output_dir <- "generated/workshop-output"
expected_chunks <- c(
  "1.1" = 3L,
  "1.2" = 1L,
  "1.3" = 2L,
  "1.4" = 2L,
  "1.5" = 1L,
  "1.6" = 2L,
  "1.7" = 2L
)

if (!requireNamespace("knitr", quietly = TRUE)) {
  stop("The knitr package is required to export the probability distributions workshop.")
}

lines <- readLines(source_file, warn = FALSE)
support_start <- grep("^## Private book-support calculations$", lines)
if (length(support_start) != 1L) {
  stop("Could not find the private support boundary in ", source_file)
}
publishable <- lines[seq_len(support_start - 1L)]

extract_chunks <- function(exercise) {
  heading <- grep(paste0("^### Exercise ", exercise, " "), publishable)
  next_heading <- grep("^### Exercise ", publishable)
  next_heading <- next_heading[next_heading > heading]

  if (length(heading) != 1L) {
    stop("Could not find Exercise ", exercise, " in ", source_file)
  }

  end <- if (length(next_heading)) next_heading[[1L]] - 1L else length(publishable)
  exercise_lines <- publishable[(heading + 1L):end]
  in_chunk <- FALSE
  chunk <- character()
  chunks <- list()

  for (line in exercise_lines) {
    if (grepl("^```\\{r(?:[ ,}])", line)) {
      in_chunk <- TRUE
      chunk <- paste0(
        "```{r, echo=TRUE, results='markup', comment='', ",
        "fig.keep='none', message=FALSE, warning=FALSE, error=FALSE}"
      )
    } else if (in_chunk && identical(line, "```")) {
      in_chunk <- FALSE
      chunks[[length(chunks) + 1L]] <- c(chunk, line)
      chunk <- character()
    } else if (in_chunk) {
      chunk <- c(chunk, line)
    }
  }

  if (in_chunk || length(chunks) != expected_chunks[[exercise]]) {
    stop("Expected ", expected_chunks[[exercise]], " complete R chunks in Exercise ", exercise, ".")
  }
  chunks
}

verbatim_hook <- function(color) {
  function(x, options) {
    if (!length(x) || !nzchar(paste(x, collapse = ""))) return("")
    paste0(
      "\\begin{Verbatim}[formatcom=\\color{", color, "}]\n",
      paste(x, collapse = ""),
      if (grepl("\\n$", paste(x, collapse = ""))) "" else "\n",
      "\\end{Verbatim}\n"
    )
  }
}

old_hooks <- knitr::knit_hooks$get(c("source", "output"))
on.exit(knitr::knit_hooks$set(source = old_hooks$source, output = old_hooks$output), add = TRUE)
knitr::knit_hooks$set(
  source = verbatim_hook("ada_blue"),
  output = verbatim_hook("ada_light_blue")
)

options(width = 65)
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

for (exercise in names(expected_chunks)) {
  chunks <- extract_chunks(exercise)
  for (i in seq_along(chunks)) {
    exercise_slug <- gsub("\\.", "-", exercise)
    output_file <- file.path(output_dir, sprintf("exercise-%s-%d.tex", exercise_slug, i))
    body <- sub("\\n+$", "", knitr::knit(text = chunks[[i]], quiet = TRUE))
    header <- c(
      "% -----------------------------------------------------------------------------",
      "% This file is automatically generated.",
      "% Do not edit manually.",
      paste0("% Source: ", source_file),
      "% -----------------------------------------------------------------------------",
      ""
    )
    compact_wrapper <- c(
      "\\par\\addvspace{\\topsep}",
      "\\begingroup",
      "\\fvset{listparameters={%",
      "  \\setlength{\\topsep}{0pt}%",
      "  \\setlength{\\partopsep}{0pt}%",
      "  \\setlength{\\parsep}{0pt}%",
      "  \\setlength{\\itemsep}{0pt}%",
      "}}",
      body,
      "\\endgroup",
      "\\par\\addvspace{\\topsep}"
    )
    writeLines(c(header, compact_wrapper), output_file, useBytes = TRUE)
    message("Generated ", output_file)
  }
}
