#!/usr/bin/env Rscript

source_file <- "notebooks/support/probability-distributions/support.Rmd"
output_dir <- "generated/workshop-output"

if (!requireNamespace("knitr", quietly = TRUE)) {
  stop("The knitr package is required to export Exercise 1.1.")
}

lines <- readLines(source_file, warn = FALSE)
start <- grep("^### Exercise 1\\.1 ", lines)
end <- grep("^### Exercise 1\\.2 ", lines)

if (length(start) != 1L || length(end) != 1L || end <= start) {
  stop("Could not find the Exercise 1.1 boundaries in ", source_file)
}

exercise <- lines[(start + 1L):(end - 1L)]
in_chunk <- FALSE
chunk <- character()
chunks <- list()

for (line in exercise) {
  if (grepl("^```\\{r(?:[ ,}])", line)) {
    in_chunk <- TRUE
    chunk <- "```{r, echo=TRUE, results='markup', comment='', fig.show='hide'}"
  } else if (in_chunk && identical(line, "```")) {
    in_chunk <- FALSE
    chunks[[length(chunks) + 1L]] <- c(chunk, line)
    chunk <- character()
  } else if (in_chunk) {
    chunk <- c(chunk, line)
  }
}

if (in_chunk || length(chunks) != 3L) {
  stop("Expected exactly three complete R chunks in Exercise 1.1.")
}

verbatim_hook <- function(color) {
  function(x, options) {
    if (!length(x) || !nzchar(paste(x, collapse = ""))) return("")
    paste0(
      "\\begin{Verbatim}[formatcom=\\color{", color, "}]\n",
      paste(x, collapse = ""),
      if (grepl("\\n$", paste(x, collapse = ""))) "" else "\n",
      "\\end{Verbatim}\n"
    )
  }
}

old_hooks <- knitr::knit_hooks$get(c("source", "output"))
on.exit(knitr::knit_hooks$set(source = old_hooks$source, output = old_hooks$output), add = TRUE)
knitr::knit_hooks$set(
  source = verbatim_hook("ada_blue"),
  output = verbatim_hook("ada_light_blue")
)

options(width = 65)
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

for (i in seq_along(chunks)) {
  output_file <- file.path(output_dir, sprintf("exercise-1-1-%d.tex", i))
  body <- sub("\\n+$", "", knitr::knit(text = chunks[[i]], quiet = TRUE))
  header <- c(
    "% Generated by scripts/export-exercise-1-1.R.",
    paste0("% Source: ", source_file, ", Exercise 1.1, chunk ", i, "."),
    "% Do not edit this file directly.",
    ""
  )
  compact_wrapper <- c(
    "\\par\\addvspace{\\topsep}",
    "\\begingroup",
    "\\fvset{listparameters={%",
    "  \\setlength{\\topsep}{0pt}%",
    "  \\setlength{\\partopsep}{0pt}%",
    "  \\setlength{\\parsep}{0pt}%",
    "  \\setlength{\\itemsep}{0pt}%",
    "}}",
    body,
    "\\endgroup",
    "\\par\\addvspace{\\topsep}"
  )
  writeLines(c(header, compact_wrapper), output_file, useBytes = TRUE)
  message("Generated ", output_file)
}
