# Render manuscript calculation snippets from registered values.

mc_values_by_id <- function(values) {
  ids <- vapply(values, function(item) item$id %||% NA_character_, character(1L))
  if (anyNA(ids) || any(!nzchar(ids))) {
    stop("Every registry value must have an `id`.", call. = FALSE)
  }
  if (any(duplicated(ids))) {
    stop("Duplicate registry value ID(s): ", paste(unique(ids[duplicated(ids)]), collapse = ", "), call. = FALSE)
  }
  stats::setNames(values, ids)
}

mc_values_by_role <- function(values) {
  roles <- vapply(values, function(item) item$role %||% NA_character_, character(1L))
  if (anyNA(roles) || any(!nzchar(roles))) {
    stop("Every registry value must have a `role`.", call. = FALSE)
  }
  if (any(duplicated(roles))) {
    stop("Duplicate registry value role(s): ", paste(unique(roles[duplicated(roles)]), collapse = ", "), call. = FALSE)
  }
  stats::setNames(values, roles)
}

mc_template_tokens <- function(lines) {
  matches <- regmatches(lines, gregexpr("\\{\\{[A-Za-z0-9_.:-]+\\}\\}", lines, perl = TRUE))
  tokens <- unique(unlist(matches, use.names = FALSE))
  if (!length(tokens)) {
    return(character())
  }
  sub("^\\{\\{", "", sub("\\}\\}$", "", tokens))
}

mc_render_template <- function(template, values, allow_roles = TRUE) {
  if (!is.character(template)) {
    stop("`template` must be a character vector.", call. = FALSE)
  }

  by_id <- mc_values_by_id(values)
  by_role <- if (allow_roles) mc_values_by_role(values) else list()
  tokens <- mc_template_tokens(template)
  missing <- character()

  replacements <- list()
  for (token in tokens) {
    if (!is.null(by_id[[token]])) {
      replacements[[token]] <- by_id[[token]]$display
    } else if (allow_roles && !is.null(by_role[[token]])) {
      replacements[[token]] <- by_role[[token]]$display
    } else {
      missing <- c(missing, token)
    }
  }

  if (length(missing)) {
    stop("Missing registered value(s) for template token(s): ", paste(missing, collapse = ", "), call. = FALSE)
  }

  out <- template
  for (token in names(replacements)) {
    out <- gsub(
      paste0("\\{\\{", token, "\\}\\}"),
      replacements[[token]],
      out,
      fixed = FALSE
    )
  }
  out
}

mc_provenance_comment <- function(entry, generator = "scripts/generate-worked-calculations.R") {
  c(
    paste0("% Generated by ", generator, "; do not edit by hand."),
    paste0("% Registry ID: ", entry$id),
    paste0("% Source notebook: ", entry$source_notebook)
  )
}

mc_render_snippet <- function(entry, template,
                              generator = "scripts/generate-worked-calculations.R") {
  if (is.null(entry$values) || !length(entry$values)) {
    stop("Registry entry must include at least one value.", call. = FALSE)
  }
  c(
    mc_provenance_comment(entry, generator = generator),
    mc_render_template(template, entry$values)
  )
}
